apiVersion: apps/v1
kind: Deployment
metadata:
  name: boardweb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boardweb
      key: board
  template:
    metadata:
      labels:
        app: boardweb
        key: board
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: key
                  operator: In
                  values:
                  - board
              topologyKey: topology.kubernetes.io/zone
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              key: board
      containers:
      - name: boardnginx
        image: 381491927681.dkr.ecr.ap-northeast-2.amazonaws.com/boardweb:latest
        ports:
        - containerPort: 80
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: boardweb
    key: board
  name: boardweb-svc
spec:
  type: NodePort
  clusterIP: 172.20.0.5
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30003
  selector:
    app: boardweb
    key: board
status:
  loadBalancer: {}
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: loginhpa
spec:
  maxReplicas: 5 
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: boardweb
  targetCPUUtilizationPercentage: 10

