apiVersion: v1
kind: Service
metadata:
  labels:
    app: loginweb
  name: loginweb-svc
spec:
  type: NodePort
  clusterIP: 10.96.0.2
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30002
  selector:
    app: loginweb
status:
  loadBalancer: {}

