apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mainweb
  name: mainweb
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mainweb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mainweb
    spec:
      containers:
      - image: 381491927681.dkr.ecr.ap-northeast-2.amazonaws.com/mainweb:v2.5
        imagePullPolicy: IfNotPresent
        name: mainweb
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-20T01:38:35Z"
  labels:
    app: mainweb
  name: mainweb-svc
  namespace: default
  resourceVersion: "1265721"
  uid: c5a259e1-a20c-4af7-874b-402f730fcf4b
spec:
  clusterIP: 172.20.114.0
  clusterIPs:
  - 172.20.114.0
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30200
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mainweb
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}

