apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: baordwas
    key: board
  name: boardwas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boardwas
      key: board
  template:
    metadata:
      labels:
        app: boardwas
        key: board
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: key
                  operator: In
                  values:
                  - board
              topologyKey: topology.kubernetes.io/zone    
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              key: board
      containers:
      - image: 381491927681.dkr.ecr.ap-northeast-2.amazonaws.com/board:v1.5
        name: boardwas
        ports:
        - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: boardwas
    key: board
  name: boardwas-svc
spec:
  clusterIP: 172.20.0.6
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: boardwas
    key: board
  type: ClusterIP
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: loginhpa
spec:
  maxReplicas: 5 
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: loginwas
  targetCPUUtilizationPercentage: 10

