apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: memberweb
    key: member
  name: memberweb
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memberweb
      key: member
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: memberweb
        key: member
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: key
                  operator: In
                  values:
                  - member
              topologyKey: topology.kubernetes.io/zone
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              key: member
      containers:
      - image: 381491927681.dkr.ecr.ap-northeast-2.amazonaws.com/memberweb:v1.1
        imagePullPolicy: IfNotPresent
        name: memberweb
        resources: {}
        terminationMessagePath: /dev/termination-log
        ports:
        - containerPort: 80
         resources:
         requests:
           cpu: 200m
           memory: 200Mi
         limits:
           cpu: 200m
           memory: 200Mi
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: memberweb
  name: memberweb-svc
  namespace: default
spec:
  clusterIP: 172.20.0.8
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30300
  selector:
    app: memberweb
    key: member
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: memberwebhpa
spec:
  maxReplicas: 5 
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: memberweb
  targetCPUUtilizationPercentage: 60
