apiVersion: v1
kind: Service
metadata:
  labels:
    app: boardweb
  name: boardweb-svc
spec:
  type: NodePort
  clusterIP: 10.96.0.5
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30003
  selector:
    app: boardweb
status:
  loadBalancer: {}

